name: seyahatname
description: "Firebase tabanlı seyahat uygulaması - Almanya, Avusturya ve İsviçre seyahatleri"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  
  # Google Sign-In
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.2
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # Utilities
  intl: 0.20.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  logger: ^2.4.0
  
  # Date & Time
  flutter_datetime_picker_plus: ^2.2.0
  
  # Connectivity
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/data/
    - assets/images/
    
