// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wwaAi9_FbRAKCK_d6wgBNNbEyxM-5aI',
    appId: '1:448618578101:web:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'seyahatname-app',
    authDomain: 'seyahatname-app.firebaseapp.com',
    storageBucket: 'seyahatname-app.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrZ-g0hV40RjYPOaKTNag',
    appId: '1:448618578101:android:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'seyahatname-app',
    storageBucket: 'seyahatname-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrZ-g0hV40RjYPOaKTNag',
    appId: '1:448618578101:ios:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'seyahatname-app',
    storageBucket: 'seyahatname-app.appspot.com',
    iosBundleId: 'com.example.seyahatname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdVl-cTICSwYKrZ-g0hV40RjYPOaKTNag',
    appId: '1:448618578101:macos:0b650370bb29e29cac3efc',
    messagingSenderId: '448618578101',
    projectId: 'seyahatname-app',
    storageBucket: 'seyahatname-app.appspot.com',
    iosBundleId: 'com.example.seyahatname',
  );
}
